apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shopregister
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # application port or container port or here docker expose port
      nodePort: 30080  # cluster node port
  type: NodePort
